site_name: Tidi
repo_url: https://github.com/pattersam/tidi
repo_name: tidi
theme:
  name: material
  features:
    - navigation.tabs
  language: en
plugins:
  - search
  - git-authors
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - src
      watch:
        - src
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
